enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

# Allow optional dependencies to fail during install
enableImmutableInstalls: false

supportedArchitectures:
  os: ["current"]
  cpu: ["current"]

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
